In [2]:
import numpy as np

In [6]:
conditional = np.array([[0.4, 0.1, 0.4, 0.1],
               [0.2, 0.3, 0.2, 0.3]])
transition = np.array([[0.8, 0.2],
              [0.4, 0.6]])
initial = np.array([0.7, 0.3])
observations = np.array([0, 2, 1, 2, 3, 0])
# observations = np.array([1,1,1,1,1,1])
T = 6

## Viterbi Algorithm

In [12]:
deltas = np.zeros((observations.shape[0], initial.shape[0]), dtype=float)
chosen = np.zeros((observations.shape[0], initial.shape[0]), dtype=int)

for i in range(initial.shape[0]):
    deltas[0][i] = initial[i] * conditional[i][observations[0]]

for t in range(1, observations.shape[0]):
    for j in range(initial.shape[0]):
        max_val = float("-inf")
        max_state = -1
        for i in range(initial.shape[0]):
            val = conditional[j][observations[t]] * transition[i][j] * deltas[t-1][i]
            print i,j,t,val
            
            if max_val < val:
                max_val = val
                max_state = i
        deltas[t][j] = max_val
        chosen[t][j] = max_state

float_formatter = lambda x: "%.8f" % x        
np.set_printoptions(formatter={'float_kind':float_formatter})
print deltas
print chosen

chosen_max = -1
chosen_max_value = float("-inf")

for i in range(initial.shape[0]):
    if chosen_max_value < deltas[T-1][i]:
        chosen_max = i
        chosen_max_value = deltas[T-1][i]

print chosen_max_value
output_sequence = str(chosen[T-1][chosen_max])

for t in range(T-1,0,-1):
    chosen_max = chosen[t][chosen_max]
    output_sequence = str(chosen_max) + " => "+ output_sequence

print "Most Likely Sequence: "+output_sequence
    

0 0 1 0.0896
1 0 1 0.0096
0 1 1 0.0112
1 1 1 0.0072
0 0 2 0.007168
1 0 2 0.000448
0 1 2 0.005376
1 1 2 0.002016
0 0 3 0.00229376
1 0 3 0.00086016
0 1 3 0.00028672
1 1 3 0.00064512
0 0 4 0.0001835008
1 0 4 2.58048e-05
0 1 4 0.0001376256
1 1 4 0.0001161216
0 0 5 5.8720256e-05
1 0 5 2.2020096e-05
0 1 5 7.340032e-06
1 1 5 1.6515072e-05
[[0.28000000 0.06000000]
 [0.08960000 0.01120000]
 [0.00716800 0.00537600]
 [0.00229376 0.00064512]
 [0.00018350 0.00013763]
 [0.00005872 0.00001652]]
[[0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 1]]
5.8720256e-05
Most Likely Sequence: 0 => 0 => 0 => 0 => 0 => 0


## P(x_1, x_2, .. x_T)

In [5]:
observations = np.array([0, 2, 1, 2, 3, 0])
# observations = np.array([1,1,1,1,1,1])
T = 6
alphas = np.zeros((observations.shape[0], initial.shape[0]))
for i in range(initial.shape[0]):
    alphas[0][i] = initial[i] * conditional[i][observations[0]]
    
for t in range(1, observations.shape[0]):
    for j in range(initial.shape[0]):
        val = 0.0
        for i in range(initial.shape[0]):
            val += transition[i][j] * alphas[t-1][i]
            
        alphas[t][j] = conditional[j][observations[t]] * val
print alphas
print "Prob: "+ str(np.sum(alphas, axis=1)[T-1]/np.sum(alphas, axis=1)[T-2])

[[0.28000000 0.06000000]
 [0.09920000 0.01840000]
 [0.00867200 0.00926400]
 [0.00425728 0.00145856]
 [0.00039892 0.00051798]
 [0.00021053 0.00007811]]
Prob: 0.314806304357
